### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by mvchn** [trngl8/the-button-php#6]
Describe developer operations

**Comment by Bujhm** [comment]
1. Setup composer https://www.hostinger.com/tutorials/how-to-install-composer
2. Run: _**composer install**_ in the project root folder
3. Run PhpUnit Test with running this command: _**composer test**_

**Comment by mvchn** [comment]
@Bujhm okay, could you create a pull request?
It can be published in the README.md

**Comment by Bujhm** [comment]
> @Bujhm okay, could you create a pull request?
> It can be published in the README.md

yes, of course, i'm planning to add here info how to run button.http also.

**Comment by mvchn** [comment]
@Bujhm 
test results:
`Invalid address: localhost:8000/api/item`
